"""empty message

Revision ID: 2f678a9eba86
Revises: 8b0ce2bf2cef
Create Date: 2016-09-28 12:03:40.551000

"""

# revision identifiers, used by Alembic.
revision = '2f678a9eba86'
down_revision = '8b0ce2bf2cef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_post',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_post')
    op.drop_table('tags')
    ### end Alembic commands ###
