"""empty message

Revision ID: c9f487e38520
Revises: a823a900ea4f
Create Date: 2016-08-31 16:46:34.601000

"""

# revision identifiers, used by Alembic.
revision = 'c9f487e38520'
down_revision = 'a823a900ea4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    op.drop_column('post', 'summary')
    op.drop_column('post', 'body_html')
    ### end Alembic commands ###
