"""empty message

Revision ID: dd503a5987b5
Revises: b4722c8968df
Create Date: 2016-08-30 16:48:54.954000

"""

# revision identifiers, used by Alembic.
revision = 'dd503a5987b5'
down_revision = 'b4722c8968df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
